//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airbag.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCat_Carrito
    {
        public int iIdCarrito { get; set; }
        public int iIdUsuario { get; set; }
        public int iIdProducto { get; set; }
        public int iCantidad { get; set; }
        public int iEstatus { get; set; }
    
        public virtual tblCat_Producto tblCat_Producto { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
