//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airbag.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCompra()
        {
            this.tblDetallesCompra = new HashSet<tblDetallesCompra>();
        }
    
        public int iIdCompra { get; set; }
        public int iIdTarjeta { get; set; }
        public int iIdUsuario { get; set; }
        public System.DateTime dtFechaCompra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetallesCompra> tblDetallesCompra { get; set; }
        public virtual tblTarjeta tblTarjeta { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
