//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airbag.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCompra()
        {
            this.tblDetallesCompra = new HashSet<tblDetallesCompra>();
        }
    
        public int iIdCompra { get; set; }
        public int iIdTarjeta { get; set; }
        public int iIdUsuario { get; set; }
        public System.DateTime dtFechaCompra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetallesCompra> tblDetallesCompra { get; set; }
        public virtual tblTarjeta tblTarjeta { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
