//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airbag.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDireccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDireccion()
        {
            this.tblDetallesCompra = new HashSet<tblDetallesCompra>();
        }
    
        public int iIdDireccionEnvio { get; set; }
        public int iIdUsuario { get; set; }
        public Nullable<int> iNumeroInterior { get; set; }
        public int iNumeroExterior { get; set; }
        public string cCalle { get; set; }
        public string cColonia { get; set; }
        public string cMunicipio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetallesCompra> tblDetallesCompra { get; set; }
    }
}
